### ISSUE TITLE
GPT generate is not working as expected

### ISSUE THREAD

**Issue by sauraz** [AlexandroMtzG/saasrock-kb#1]
The data generation functionality is not performing as intended, and the absence of error logs makes it challenging to pinpoint the issue. Additionally, the loading bar continues to spin indefinitely without any timeout.

<img width="1028" alt="image" src="https://github.com/AlexandroMtzG/saasrock-kb/assets/108146397/fa0a17b9-d356-4bfa-8897-bcf962141200">

**Comment by AlexandroMtzG** [comment]
@sauraz I don't have any issues (see video). Is your `OPENAI_API_KEY` .env variable set?

https://github.com/AlexandroMtzG/saasrock-kb/assets/8606530/ff86e864-0ddc-466e-a376-0c70749e945d

**Comment by sauraz** [comment]
Thank you for the quick reply. I see that my free credits on OPEN API have been expired. It was throwing a 429.
